### ISSUE TITLE
Inline code font issue

### ISSUE THREAD

**Issue by yoyurec** [nmartin84/logseq-chocolate#5]
Issue when font not installed ("iA Writer Duo S", "SF Mono"):
![image](https://user-images.githubusercontent.com/137919/187563683-69f27951-475a-4649-bc77-69ddaae65100.png)

You can set more fallback fonts:
```css
.white-theme :not(pre)>code {
...
    font-family: "iA Writer Duo S", "SF Mono", "FiraCode Nerd Font", "Fira Code", Monaco, Menlo, Consolas, "COURIER NEW", monospace;
...
}
```
