### ISSUE TITLE
Few CSS issues with main containers

### ISSUE THREAD

**Issue by yoyurec** [nmartin84/logseq-chocolate#6]
Right sidebar resize ruler shifted, suggest to delete few properties:
```css
#main-content-container {
    margin-left: 10px;
    margin-right: 10px
}
.cp__sidebar-main-content > div {
    margin: 0px -10px;
}
```

\+ Fix banner::

```css
.theme-inner:not(.ls-wide-mode) div#banner {
/* change `width` to `max-width` */
    max-width: var(--ls-main-content-max-width);
}
.is-banner-active .cp__sidebar-main-content > div {
    border-radius: 0 0 var(--cl-border-max) var(--cl-border-max);
}
.is-banner-active #banner {
    border-radius: var(--cl-border-max) var(--cl-border-max) 0 0;
    box-shadow: rgb(0 0 0 / 20%) 0px -4px 10px 4px; /* for example */
}
```
